name: HACS Validation

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  validate:
    name: Run HACS Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@22.5.0
        with:
          category: integration
